### ISSUE TITLE
Getting an empty object when loading a Json file

### ISSUE THREAD

**Issue by lou-garavaglia** [robshakir/pyangbind#119] opened 2017-03-28 00:18 UTC
I'm trying to use load to populate a simple Yang model and I am getting an empty object.  I have tried your example and it works fine so I am at a loss to explain what is going on.  

Here is my Yang model (**mef-fd-shrt.yang**):

module mef-fd-shrt {
    namespace "urn:ltg:mef-fd-shrt";
    prefix "mef-fd-shrt";
    container fds {
        list fd {
            key "name";
            leaf name {
                type string;
            }
        }
    }
}

Here is the data I am trying to load (**mef-fd-shrt.json**):
{
    "fds": {
        "fd": {
            "name": "fd0"
        }
    }
}

Here is the script I am running to load it (**fd_shrt.py**)
#!/usr/bin/env python

from __future__ import print_function, unicode_literals
import pyangbind.lib.pybindJSON as pybindJSON

import os
from binding.mef_fd_shrt import mef_fd_shrt
import binding.mef_fd_shrt
new_fd = pybindJSON.load(os.path.join("json", "mef-fd-shrt.json"), binding.mef_fd_shrt, "mef_fd_shrt")

print(pybindJSON.dumps(new_fd, mode="ietf"))

Here is the **output**:
> python fd_shrt.py
{}

Here is the **binding**:

[mef_fd_shrt.txt](https://github.com/robshakir/pyangbind/files/874138/mef_fd_shrt.txt)

**Comment by JoseIgnacioTamayo** [comment] 2024-02-23 07:53
I think the problem is a bit syntax in your json:

```
{
"fds": {
   "fd": {
    "fd0": {
        "name": "fd0"
     }
   }
 }
}
```

Could you give this a try?

**Comment by JoseIgnacioTamayo** [comment] 2024-03-27 21:02
Closing issues without recent activity

**Closed by JoseIgnacioTamayo** 2024-03-27 21:02 UTC
