### ISSUE TITLE
__add_metadata is not adding the @metadata object to JSON or XML

### ISSUE THREAD

**Issue by vicluq** [robshakir/pyangbind#307] opened 2023-07-26 18:18 UTC
```python
camera1.profile._add_metadata("inactive", True)
```

```json
{
    "camera:camera-group": {
        "camera": [
            {
                "name": "corner1",
                "camera-type": "2d",
                "protocol": "rtsp",
                "ip": "127.222.111.3",
                "profile": "admin:12345678"
            }
        ]
    }
}
```

```xml
<camera xmlns="tesst">
  <camera-group>
    <camera>
      <name>corner1</name>
      <camera-type>2d</camera-type>
      <protocol>rtsp</protocol>
      <ip>127.222.111.3</ip>
      <profile>admin:12345678</profile>
    </camera>
  </camera-group>
</camera>
```

**Comment by JoseIgnacioTamayo** [comment] 2023-07-28 05:44
Hi vicluq,

Reproducing your issue is key to understand it and fix it.

 * What YANG Model are you using? And how are you calling pyang + pyangbind to render it into a Python class ?
 * How are you creating the YANGBaseClass object (loading a JSON file, or in Python directly) ?
 * How are you generating the JSON and XML outputs?
 * With a Python debugger, can you check what is the Object like after you call ._add_metadata()
 * What is your expected output? Maybe the problem is at this stage.

If in the process of troubleshooting and debugging this, you find a bug in pyangbind that causes it, please feel free to propose a PullRequest.

Looking forward to helping you with the issue.

**Comment by JoseIgnacioTamayo** [comment] 2023-09-28 06:46
Closing, as there was no follow up on the issue.

**Closed by JoseIgnacioTamayo** 2023-09-28 06:46 UTC
